name: Docker Image CI

on:
  push:
    tags: 
    - "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_HUB }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build && push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_HUB }}/mparchin/${{ github.repository }}:${{ github.ref_name }},${{ vars.DOCKER_HUB }}/mparchin/${{ github.repository }}:latest
        cache-from: type=registry,ref=${{ vars.DOCKER_HUB }}/mparchin/${{ github.repository }}-cache
        cache-to: type=registry,ref=${{ vars.DOCKER_HUB }}/mparchin/${{ github.repository }}-cache,mode=max
